/** Thresholds and blocklists — Architecture §11 */

export const THRESHOLDS = {
  ASSUMPTION_IMPACT_MIN: 0.65,
  RISK_DECISION_IMPACT_MIN: 0.7,
  MIN_ANSWER_TOKENS_FOR_JUDGMENT: 50,
  MAX_DISPLAYED_ASSUMPTIONS: 3,
  MAX_DISPLAYED_RISKS: 3,
  MAX_DISPLAYED_VERIFICATIONS: 3,
  MAX_VERIFICATION_EFFORT_MINUTES: 30,
} as const;

/** Phrases that indicate generic AI disclaimers — never show as risks */
export const GENERIC_DISCLAIMER_PATTERNS = [
  /ai may (make mistakes|be wrong|hallucinate)/i,
  /always (verify|double-check|fact-check)/i,
  /not a substitute for (professional|legal|medical)/i,
  /information may be outdated/i,
  /consult (a|your) (doctor|lawyer|professional)/i,
  /generated by (an )?ai/i,
] as const;

/** Trivial / universal premises — hide as assumptions */
export const TRIVIAL_ASSUMPTION_PATTERNS = [
  /companies want (to )?profit/i,
  /people (generally )?prefer/i,
  /the (world|economy) is complex/i,
  /results may vary/i,
  /it depends on (the )?context/i,
] as const;

/** Vague verification phrases — suppress */
export const VAGUE_VERIFICATION_PATTERNS = [
  /^research more$/i,
  /^be careful$/i,
  /^double-check$/i,
  /^verify (this|it)$/i,
  /^consult an expert$/i,
  /^use your (own )?judgment$/i,
  /^check (the )?sources?$/i,
] as const;

export const CHITCHAT_PATTERNS = [
  /^(hi|hello|hey|thanks|thank you|ok|okay|bye|goodbye)[\s!.?]*$/i,
  /^how are you/i,
  /^what'?s up/i,
] as const;

export const CREATIVE_PATTERNS = [
  /\b(write|compose|draft)\b.*\b(poem|story|song|lyrics|haiku|fiction)\b/i,
  /\b(creative writing|short story|fanfic)\b/i,
] as const;

export const HIGH_STAKES_PATTERNS = [
  /\b(invest|budget|contract|legal|lawsuit|fda|compliance|hire|fire|layoff)\b/i,
  /\b(medical|diagnos|prescri|dosage|patient)\b/i,
  /\b(acquisition|merger|ipo|earnings|revenue forecast)\b/i,
  /\b(should we|go\/no-go|decide whether)\b/i,
  /\b(client|customer-facing|external|publish|release)\b/i,
] as const;

export const VERY_HIGH_STAKES_PATTERNS = [
  /\b(executive|board|ceo|cfo|cto|critical|mission-critical)\b/i,
  /\b(go\/no-go|bet the company|material impact|regulatory filing)\b/i,
  /\b(layoff|acquisition|merger|ipo|sec filing|fda approval)\b/i,
] as const;

export const DECISION_INTENT_PATTERNS = [
  /\b(should (i|we)|recommend|decide|choose between|pros and cons)\b/i,
  /\b(business case|roadmap priority|strategy for)\b/i,
] as const;

export const PLANNING_INTENT_PATTERNS = [
  /\b(plan|roadmap|timeline|milestone|okr|project plan)\b/i,
  /\b(how (do|should) we (implement|roll out|launch))\b/i,
] as const;
